import { useState, useMemo } from 'react';
import {
  RefreshCw, Plus, Pause, Play, Trash2, Edit3,
  Clock, Calendar, AlertCircle,
} from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { useAppContext } from '../../../context/AppContext';
import { RecurringRule } from '../../../shared/types';
import { Modal } from '../../../shared/components/ui/Modal';
import { Button } from '../../../shared/components/ui/Button';
import { Input, Select } from '../../../shared/components/ui/Input';
import { EmptyState } from '../../../shared/components/ui/EmptyState';
import { CategoryIcon } from '../../../shared/components/ui/CategoryIcon';
import { formatCurrency, formatDate } from '../../../shared/utils/helpers';

const FREQUENCY_OPTIONS = [
  { value: 'daily', label: 'Daily' },
  { value: 'weekly', label: 'Weekly' },
  { value: 'monthly', label: 'Monthly' },
  { value: 'yearly', label: 'Yearly' },
];

const frequencyColors: Record<string, string> = {
  daily: 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300',
  weekly: 'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-300',
  monthly: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300',
  yearly: 'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
};

function daysUntil(dateStr: string): number {
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  const target = new Date(dateStr + 'T00:00:00');
  return Math.ceil((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
}

interface RuleFormState {
  name: string;
  type: 'income' | 'expense';
  amount: string;
  categoryId: string;
  accountId: string;
  frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
  startDate: string;
  endDate: string;
  notes: string;
  paymentMethod: string;
}

const emptyForm: RuleFormState = {
  name: '',
  type: 'expense',
  amount: '',
  categoryId: '',
  accountId: '',
  frequency: 'monthly',
  startDate: new Date().toISOString().split('T')[0],
  endDate: '',
  notes: '',
  paymentMethod: '',
};

export function RecurringPage() {
  const { state, actions } = useAppContext();
  const { recurringRules, categories, accounts, transactions, settings } = state;

  const [showModal, setShowModal] = useState(false);
  const [editingRule, setEditingRule] = useState<RecurringRule | null>(null);
  const [form, setForm] = useState<RuleFormState>(emptyForm);

  // Filter categories by selected type
  const filteredCategories = useMemo(
    () => categories.filter((c) => c.type === form.type),
    [categories, form.type]
  );

  // Recent auto-generated transactions
  const recentAutoGenerated = useMemo(
    () =>
      transactions
        .filter((t) => t.isRecurring)
        .sort((a, b) => b.date.localeCompare(a.date))
        .slice(0, 10),
    [transactions]
  );

  const activeRules = useMemo(
    () => recurringRules.filter((r) => r.isActive),
    [recurringRules]
  );

  const inactiveRules = useMemo(
    () => recurringRules.filter((r) => !r.isActive),
    [recurringRules]
  );

  const handleOpenAdd = () => {
    setEditingRule(null);
    setForm(emptyForm);
    setShowModal(true);
  };

  const handleOpenEdit = (rule: RecurringRule) => {
    setEditingRule(rule);
    setForm({
      name: rule.name,
      type: rule.type,
      amount: rule.amount.toString(),
      categoryId: rule.categoryId,
      accountId: rule.accountId || '',
      frequency: rule.frequency,
      startDate: rule.startDate,
      endDate: rule.endDate || '',
      notes: rule.notes,
      paymentMethod: rule.paymentMethod || '',
    });
    setShowModal(true);
  };

  const handleSave = async () => {
    const amount = parseFloat(form.amount);
    if (!form.name.trim() || isNaN(amount) || amount <= 0 || !form.categoryId) return;

    const now = new Date().toISOString();

    if (editingRule) {
      const updates: Partial<RecurringRule> = {
        name: form.name.trim(),
        type: form.type,
        amount,
        categoryId: form.categoryId,
        accountId: form.accountId || undefined,
        paymentMethod: (form.paymentMethod || undefined) as RecurringRule['paymentMethod'],
        notes: form.notes,
        frequency: form.frequency,
        startDate: form.startDate,
        endDate: form.endDate || undefined,
        updatedAt: now,
      };
      // Recompute nextDueDate if frequency or startDate changed
      if (form.frequency !== editingRule.frequency || form.startDate !== editingRule.startDate) {
        updates.nextDueDate = form.startDate;
      }
      await actions.updateRecurringRule(editingRule.id, updates);
    } else {
      const rule: RecurringRule = {
        id: uuidv4(),
        name: form.name.trim(),
        type: form.type,
        amount,
        categoryId: form.categoryId,
        accountId: form.accountId || undefined,
        paymentMethod: (form.paymentMethod || undefined) as RecurringRule['paymentMethod'],
        notes: form.notes,
        frequency: form.frequency,
        startDate: form.startDate,
        endDate: form.endDate || undefined,
        nextDueDate: form.startDate,
        isActive: true,
        createdAt: now,
        updatedAt: now,
      };
      await actions.addRecurringRule(rule);
    }

    setShowModal(false);
    setEditingRule(null);
    setForm(emptyForm);
  };

  const handleTogglePause = async (rule: RecurringRule) => {
    await actions.updateRecurringRule(rule.id, { isActive: !rule.isActive });
  };

  const handleDelete = async (id: string) => {
    await actions.deleteRecurringRule(id);
  };

  const getCategoryInfo = (categoryId: string) => {
    return categories.find((c) => c.id === categoryId);
  };

  const getAccountName = (accountId?: string) => {
    if (!accountId) return null;
    return accounts.find((a) => a.id === accountId)?.name || null;
  };

  const getRuleStatus = (rule: RecurringRule): { label: string; color: string } => {
    if (!rule.isActive) {
      if (rule.endDate && rule.nextDueDate > rule.endDate) {
        return { label: 'Expired', color: 'bg-red-100 text-red-700 dark:bg-red-900/40 dark:text-red-300' };
      }
      return { label: 'Paused', color: 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400' };
    }
    return { label: 'Active', color: 'bg-green-100 text-green-700 dark:bg-green-900/40 dark:text-green-300' };
  };

  const paymentMethodOptions = [
    { value: '', label: 'None' },
    { value: 'upi', label: 'UPI' },
    { value: 'cash', label: 'Cash' },
    { value: 'card', label: 'Card' },
    { value: 'net_banking', label: 'Net Banking' },
    { value: 'cheque', label: 'Cheque' },
    { value: 'auto_debit', label: 'Auto Debit' },
    { value: 'other', label: 'Other' },
  ];

  const renderRuleCard = (rule: RecurringRule) => {
    const category = getCategoryInfo(rule.categoryId);
    const accountName = getAccountName(rule.accountId);
    const status = getRuleStatus(rule);
    const days = daysUntil(rule.nextDueDate);

    return (
      <div
        key={rule.id}
        className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 p-4 shadow-sm hover:shadow-md transition-shadow"
      >
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-3 min-w-0">
            {category && (
              <div
                className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl"
                style={{ backgroundColor: category.color + '20' }}
              >
                <CategoryIcon icon={category.icon} size={20} color={category.color} />
              </div>
            )}
            <div className="min-w-0">
              <h3 className="font-semibold text-gray-900 dark:text-gray-100 truncate">{rule.name}</h3>
              <div className="flex flex-wrap items-center gap-2 mt-1">
                <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${frequencyColors[rule.frequency]}`}>
                  {rule.frequency.charAt(0).toUpperCase() + rule.frequency.slice(1)}
                </span>
                <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${status.color}`}>
                  {status.label}
                </span>
                {category && (
                  <span className="text-xs text-gray-500 dark:text-gray-400">{category.name}</span>
                )}
              </div>
            </div>
          </div>

          <div className="text-right shrink-0">
            <p className={`text-lg font-bold ${rule.type === 'income' ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
              {rule.type === 'income' ? '+' : '-'}{formatCurrency(rule.amount, settings)}
            </p>
            {accountName && (
              <p className="text-xs text-gray-500 dark:text-gray-400">{accountName}</p>
            )}
          </div>
        </div>

        {/* Due date info */}
        <div className="mt-3 flex items-center gap-4 text-xs text-gray-500 dark:text-gray-400">
          <span className="flex items-center gap-1">
            <Calendar size={12} />
            Next: {formatDate(rule.nextDueDate, settings.dateFormat)}
          </span>
          {rule.isActive && (
            <span className="flex items-center gap-1">
              <Clock size={12} />
              {days === 0
                ? 'Due today'
                : days < 0
                  ? `Overdue by ${Math.abs(days)} day${Math.abs(days) !== 1 ? 's' : ''}`
                  : `In ${days} day${days !== 1 ? 's' : ''}`}
            </span>
          )}
          {rule.lastGeneratedDate && (
            <span>Last generated: {formatDate(rule.lastGeneratedDate, settings.dateFormat)}</span>
          )}
        </div>

        {/* Actions */}
        <div className="mt-3 flex items-center gap-2 border-t border-gray-100 dark:border-gray-700 pt-3">
          <button
            onClick={() => handleOpenEdit(rule)}
            className="flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-medium text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
          >
            <Edit3 size={14} /> Edit
          </button>
          <button
            onClick={() => handleTogglePause(rule)}
            className="flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-medium text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors"
          >
            {rule.isActive ? <><Pause size={14} /> Pause</> : <><Play size={14} /> Resume</>}
          </button>
          <button
            onClick={() => handleDelete(rule.id)}
            className="flex items-center gap-1 rounded-lg px-2 py-1 text-xs font-medium text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 transition-colors"
          >
            <Trash2 size={14} /> Delete
          </button>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Recurring Transactions</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            Automate repeating income and expenses
          </p>
        </div>
        <Button icon={<Plus size={18} />} onClick={handleOpenAdd}>
          Add Recurring
        </Button>
      </div>

      {/* Empty State */}
      {recurringRules.length === 0 ? (
        <EmptyState
          icon={<RefreshCw size={32} />}
          title="No recurring transactions yet"
          description="Add rent, subscriptions, salary, EMIs, and other repeating transactions to auto-generate them on schedule."
          action={
            <Button icon={<Plus size={18} />} onClick={handleOpenAdd}>
              Add Your First Recurring Rule
            </Button>
          }
        />
      ) : (
        <>
          {/* Active Rules */}
          {activeRules.length > 0 && (
            <div>
              <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">
                Active Rules ({activeRules.length})
              </h2>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {activeRules.map(renderRuleCard)}
              </div>
            </div>
          )}

          {/* Inactive Rules */}
          {inactiveRules.length > 0 && (
            <div>
              <h2 className="mb-3 text-lg font-semibold text-gray-500 dark:text-gray-400">
                Paused / Expired ({inactiveRules.length})
              </h2>
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {inactiveRules.map(renderRuleCard)}
              </div>
            </div>
          )}
        </>
      )}

      {/* Recent Auto-Generated Transactions */}
      {recentAutoGenerated.length > 0 && (
        <div>
          <h2 className="mb-3 text-lg font-semibold text-gray-900 dark:text-gray-100">
            Recent Auto-Generated
          </h2>
          <div className="rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 overflow-hidden">
            <div className="divide-y divide-gray-100 dark:divide-gray-700">
              {recentAutoGenerated.map((tx) => {
                const cat = getCategoryInfo(tx.categoryId);
                return (
                  <div key={tx.id} className="flex items-center gap-3 px-4 py-3">
                    {cat && (
                      <div
                        className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg"
                        style={{ backgroundColor: cat.color + '20' }}
                      >
                        <CategoryIcon icon={cat.icon} size={16} color={cat.color} />
                      </div>
                    )}
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 dark:text-gray-100 truncate">
                        {tx.notes || cat?.name || 'Transaction'}
                      </p>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        {formatDate(tx.date, settings.dateFormat)}
                      </p>
                    </div>
                    <p className={`text-sm font-semibold ${tx.type === 'income' ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                      {tx.type === 'income' ? '+' : '-'}{formatCurrency(tx.amount, settings)}
                    </p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}

      {/* Add/Edit Modal */}
      <Modal
        isOpen={showModal}
        onClose={() => { setShowModal(false); setEditingRule(null); }}
        title={editingRule ? 'Edit Recurring Rule' : 'Add Recurring Rule'}
        size="lg"
      >
        <div className="space-y-4">
          {/* Rule name */}
          <Input
            label="Rule Name"
            placeholder="e.g., Rent, Netflix, Salary"
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
          />

          {/* Type toggle */}
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Type</label>
            <div className="flex rounded-lg border border-gray-300 dark:border-gray-600 overflow-hidden">
              <button
                type="button"
                className={`flex-1 px-4 py-2 text-sm font-medium transition-colors ${
                  form.type === 'expense'
                    ? 'bg-red-600 text-white'
                    : 'bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600'
                }`}
                onClick={() => setForm({ ...form, type: 'expense', categoryId: '' })}
              >
                Expense
              </button>
              <button
                type="button"
                className={`flex-1 px-4 py-2 text-sm font-medium transition-colors ${
                  form.type === 'income'
                    ? 'bg-green-600 text-white'
                    : 'bg-white dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-50 dark:hover:bg-gray-600'
                }`}
                onClick={() => setForm({ ...form, type: 'income', categoryId: '' })}
              >
                Income
              </button>
            </div>
          </div>

          {/* Amount */}
          <Input
            label="Amount"
            type="number"
            min="0"
            step="0.01"
            placeholder="0.00"
            value={form.amount}
            onChange={(e) => setForm({ ...form, amount: e.target.value })}
          />

          {/* Category */}
          <Select
            label="Category"
            value={form.categoryId}
            onChange={(e) => setForm({ ...form, categoryId: e.target.value })}
            options={[
              { value: '', label: 'Select category...' },
              ...filteredCategories.map((c) => ({ value: c.id, label: c.name })),
            ]}
          />

          {/* Account (optional) */}
          <Select
            label="Account (optional)"
            value={form.accountId}
            onChange={(e) => setForm({ ...form, accountId: e.target.value })}
            options={[
              { value: '', label: 'None' },
              ...accounts.filter((a) => a.isActive).map((a) => ({ value: a.id, label: a.name })),
            ]}
          />

          {/* Payment Method */}
          <Select
            label="Payment Method (optional)"
            value={form.paymentMethod}
            onChange={(e) => setForm({ ...form, paymentMethod: e.target.value })}
            options={paymentMethodOptions}
          />

          {/* Frequency */}
          <Select
            label="Frequency"
            value={form.frequency}
            onChange={(e) => setForm({ ...form, frequency: e.target.value as RuleFormState['frequency'] })}
            options={FREQUENCY_OPTIONS}
          />

          {/* Start Date */}
          <Input
            label="Start Date"
            type="date"
            value={form.startDate}
            onChange={(e) => setForm({ ...form, startDate: e.target.value })}
          />

          {/* End Date (optional) */}
          <Input
            label="End Date (optional)"
            type="date"
            value={form.endDate}
            onChange={(e) => setForm({ ...form, endDate: e.target.value })}
            helperText="Leave empty for no end date"
          />

          {/* Notes */}
          <div>
            <label className="mb-1.5 block text-sm font-medium text-gray-700 dark:text-gray-300">Notes</label>
            <textarea
              value={form.notes}
              onChange={(e) => setForm({ ...form, notes: e.target.value })}
              placeholder="Optional notes..."
              rows={2}
              className="w-full rounded-lg border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm text-gray-900 dark:text-gray-100 dark:bg-gray-700 placeholder-gray-400 dark:placeholder-gray-500 focus:border-primary-500 focus:outline-none focus:ring-2 focus:ring-primary-500/20"
            />
          </div>

          {/* Info */}
          <div className="flex items-start gap-2 rounded-lg bg-blue-50 dark:bg-blue-900/20 p-3 text-xs text-blue-700 dark:text-blue-300">
            <AlertCircle size={16} className="shrink-0 mt-0.5" />
            <p>
              Transactions will be auto-generated when you open the app on or after the due date.
              The first transaction will be created on the start date.
            </p>
          </div>

          {/* Buttons */}
          <div className="flex justify-end gap-3 pt-2">
            <Button variant="secondary" onClick={() => { setShowModal(false); setEditingRule(null); }}>
              Cancel
            </Button>
            <Button
              onClick={handleSave}
              disabled={!form.name.trim() || !form.amount || parseFloat(form.amount) <= 0 || !form.categoryId}
            >
              {editingRule ? 'Update Rule' : 'Create Rule'}
            </Button>
          </div>
        </div>
      </Modal>
    </div>
  );
}
